# Generated by Django 6.1 on 2026-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='full_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repository_url',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='event', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
