# Generated by Django 6.1 on 2026-09-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_description_project_full_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
